# Generated by Django 2.1.1 on 2019-04-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0012_output_mmr_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='bits',
            field=models.IntegerField(default=437004818),
            preserve_default=False,
        ),
    ]
