# Generated by Django 2.1.1 on 2019-04-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0013_block_bits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='total_difficulty',
            field=models.IntegerField(),
        ),
    ]
