# Generated by Django 2.1.1 on 2019-11-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0014_auto_20190409_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(max_length=64)),
                ('commitment', models.CharField(max_length=66)),
            ],
        ),
        migrations.CreateModel(
            name='TokenKernel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.TextField()),
                ('token_type', models.CharField(max_length=64)),
                ('lock_height', models.IntegerField()),
                ('excess', models.CharField(max_length=66)),
                ('excess_sig', models.CharField(max_length=142)),
            ],
        ),
        migrations.CreateModel(
            name='TokenOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.TextField(choices=[('Transaction', 'Transaction'), ('Coinbase', 'Coinbase'), ('TokenIsuue', 'TokenIsuue'), ('TokenTransaction', 'TokenTransaction')])),
                ('token_type', models.CharField(max_length=64)),
                ('commit', models.CharField(max_length=66)),
                ('spent', models.BooleanField()),
                ('proof', models.TextField(null=True)),
                ('proof_hash', models.CharField(max_length=64)),
                ('block_height', models.IntegerField(null=True)),
                ('merkle_proof', models.TextField(null=True)),
                ('mmr_index', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='token_issue_proof_root',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='token_kernel_root',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='token_output_root',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='token_range_proof_root',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='token_type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='output_type',
            field=models.TextField(choices=[('Transaction', 'Transaction'), ('Coinbase', 'Coinbase'), ('TokenIsuue', 'TokenIsuue'), ('TokenTransaction', 'TokenTransaction')]),
        ),
        migrations.AddField(
            model_name='tokenoutput',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blockchain.Block'),
        ),
        migrations.AddField(
            model_name='tokenkernel',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blockchain.Block'),
        ),
        migrations.AddField(
            model_name='tokeninput',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blockchain.Block'),
        ),
    ]
