# Generated by Django 2.1.1 on 2020-07-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0015_auto_20191126_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='mask',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
