# Generated by Django 2.1.1 on 2020-07-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0016_block_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='output_mmr_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
