# Generated by Django 2.1.1 on 2020-07-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0017_block_output_mmr_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='kernel_mmr_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
